# Copyright (c) 2025, Palo Alto Networks
#
# Licensed under the Polyform Internal Use License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# https://polyformproject.org/licenses/internal-use/1.0.0
# (or)
# https://github.com/polyformproject/polyform-licenses/blob/76a278c4/PolyForm-Internal-Use-1.0.0.md
#
# As far as the law allows, the software comes as is, without any warranty
# or condition, and the licensor will not be liable to you for any damages
# arising out of these terms or the use or nature of the software, under
# any kind of legal claim.

"""
AISec API service

OpenAPI Specification for the AI Runtime Security API service

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aisecurity.generated_openapi_client.models.threat_scan_report_object import ThreatScanReportObject


class TestThreatScanReportObject(unittest.TestCase):
    """ThreatScanReportObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThreatScanReportObject:
        """Test ThreatScanReportObject
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ThreatScanReportObject`
        """
        model = ThreatScanReportObject()
        if include_optional:
            return ThreatScanReportObject(
                source = '',
                report_id = '',
                scan_id = '',
                req_id = 56,
                transaction_id = '',
                session_id = '',
                detection_results = [
                    aisecurity.generated_openapi_client.models.detection_service_result_object.DetectionServiceResultObject(
                        data_type = '',
                        detection_service = '',
                        verdict = '',
                        action = '',
                        metadata = aisecurity.generated_openapi_client.models.ds_result_metadata.DSResultMetadata(
                            ecosystem = 'mcp',
                            method = 'tools/call',
                            server_name = 'MCP server',
                            tool_invoked = 'get_file',
                            direction = 'input', ),
                        result_detail = aisecurity.generated_openapi_client.models.ds_detail_result_object.DSDetailResultObject(
                            urlf_report = [
                                aisecurity.generated_openapi_client.models.urlf_entry_object.UrlfEntryObject(
                                    url = '',
                                    risk_level = '',
                                    action = '',
                                    categories = [
                                        ''
                                        ], )
                                ],
                            dlp_report = aisecurity.generated_openapi_client.models.dlp_report_object.DlpReportObject(
                                dlp_report_id = '',
                                dlp_profile_name = '',
                                dlp_profile_id = '',
                                dlp_profile_version = 56,
                                data_pattern_rule1_verdict = '',
                                data_pattern_rule2_verdict = '',
                                data_pattern_detection_offsets = [
                                    aisecurity.generated_openapi_client.models.dlp_pattern_detections_object.DlpPatternDetectionsObject(
                                        data_pattern_id = '',
                                        version = 56,
                                        name = '',
                                        high_confidence_detections = [
                                            [
                                                56
                                                ]
                                            ],
                                        medium_confidence_detections = [
                                            [
                                                56
                                                ]
                                            ],
                                        low_confidence_detections = , )
                                    ], ),
                            dlp_snippets = aisecurity.generated_openapi_client.models.dlp_snippet_object.DlpSnippetObject(
                                meta = aisecurity.generated_openapi_client.models.dlp_snippet_meta.DlpSnippetMeta(
                                    data_pattern = '',
                                    confidence_level = 'low',
                                    data_pattern_type = '',
                                    occurrence = 56, ),
                                snippets = [
                                    ''
                                    ], ),
                            pi_report = aisecurity.generated_openapi_client.models.pi_report_object.PiReportObject(
                                verdict = '', ),
                            pi_snippets = [
                                ''
                                ],
                            dbs_report = [
                                aisecurity.generated_openapi_client.models.dbs_entry_object.DbsEntryObject(
                                    sub_type = '',
                                    verdict = '',
                                    action = '', )
                                ],
                            dbs_snippets = ,
                            tc_report = aisecurity.generated_openapi_client.models.tc_report_object.TcReportObject(
                                confidence = '',
                                verdict = '',
                                toxic_categories = [
                                    ''
                                    ], ),
                            tc_snippets = ,
                            source_code_snippets = ,
                            source_code_report = aisecurity.generated_openapi_client.models.source_code_report_object.SourceCodeReportObject(
                                verdict = '',
                                confidence_score = 1.337,
                                code_present = True,
                                category = '', ),
                            mc_report = aisecurity.generated_openapi_client.models.mc_report_object.McReportObject(
                                all_code_blocks = [
                                    ''
                                    ],
                                code_analysis_by_type = [
                                    aisecurity.generated_openapi_client.models.mc_entry_object.McEntryObject(
                                        file_type = '',
                                        code_sha256 = '', )
                                    ],
                                verdict = '',
                                malware_script_report = aisecurity.generated_openapi_client.models.malware_report_object.MalwareReportObject(
                                    verdict = '', ),
                                command_injection_report = [
                                    aisecurity.generated_openapi_client.models.cmd_entry_object.CmdEntryObject(
                                        code_block = '',
                                        verdict = '', )
                                    ],
                                truncation_info = aisecurity.generated_openapi_client.models.truncation_info_object.TruncationInfoObject(
                                    payload_truncated = True,
                                    original_payload_length = 56,
                                    truncated_payload_length = 56,
                                    truncation_mode = 'tail', ), ),
                            agent_report = aisecurity.generated_openapi_client.models.agent_report_object.AgentReportObject(
                                model_verdict = '',
                                agent_framework = '',
                                agent_patterns = [
                                    aisecurity.generated_openapi_client.models.agent_entry_object.AgentEntryObject(
                                        category_type = '',
                                        verdict = '', )
                                    ], ),
                            topic_guardrails_report = aisecurity.generated_openapi_client.models.tg_report_object.TgReportObject(
                                allowed_topic_list = '',
                                blocked_topic_list = '',
                                allowed_topics = [
                                    ''
                                    ],
                                blocked_topics = [
                                    ''
                                    ], ),
                            cg_report = aisecurity.generated_openapi_client.models.cg_report_object.CgReportObject(
                                status = '',
                                explanation = '',
                                category = '', ), ), )
                    ]
            )
        else:
            return ThreatScanReportObject(
        )
        """

    def testThreatScanReportObject(self):
        """Test ThreatScanReportObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
