# Copyright (c) 2025, Palo Alto Networks
#
# Licensed under the Polyform Internal Use License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# https://polyformproject.org/licenses/internal-use/1.0.0
# (or)
# https://github.com/polyformproject/polyform-licenses/blob/76a278c4/PolyForm-Internal-Use-1.0.0.md
#
# As far as the law allows, the software comes as is, without any warranty
# or condition, and the licensor will not be liable to you for any damages
# arising out of these terms or the use or nature of the software, under
# any kind of legal claim.

"""
AISec API service

OpenAPI Specification for the AI Runtime Security API service

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aisecurity.generated_openapi_client.models.async_scan_object import AsyncScanObject


class TestAsyncScanObject(unittest.TestCase):
    """AsyncScanObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AsyncScanObject:
        """Test AsyncScanObject
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AsyncScanObject`
        """
        model = AsyncScanObject()
        if include_optional:
            return AsyncScanObject(
                req_id = 56,
                scan_req = aisecurity.generated_openapi_client.models.scan_request.ScanRequest(
                    tr_id = '',
                    session_id = '',
                    transaction_id = '',
                    ai_profile = aisecurity.generated_openapi_client.models.ai_profile.AiProfile(
                        profile_id = '',
                        profile_name = '', ),
                    metadata = aisecurity.generated_openapi_client.models.metadata.Metadata(
                        app_name = '',
                        app_user = '',
                        ai_model = '',
                        user_ip = '',
                        agent_meta = aisecurity.generated_openapi_client.models.agent_meta.AgentMeta(
                            agent_id = '',
                            agent_version = '',
                            agent_arn = '', ), ),
                    contents = [
                        aisecurity.generated_openapi_client.models.scan_request_contents_inner.ScanRequestContentsInner(
                            prompt = '',
                            response = '',
                            code_prompt = '',
                            code_response = '',
                            context = '',
                            tool_event = aisecurity.generated_openapi_client.models.tool_event.ToolEvent(
                                input = '{"file_key":"abc123"}',
                                output = '{"content":[{"type":"text","text":"Fetched file"}]}', ), )
                        ], )
            )
        else:
            return AsyncScanObject(
                req_id = 56,
                scan_req = aisecurity.generated_openapi_client.models.scan_request.ScanRequest(
                    tr_id = '',
                    session_id = '',
                    transaction_id = '',
                    ai_profile = aisecurity.generated_openapi_client.models.ai_profile.AiProfile(
                        profile_id = '',
                        profile_name = '', ),
                    metadata = aisecurity.generated_openapi_client.models.metadata.Metadata(
                        app_name = '',
                        app_user = '',
                        ai_model = '',
                        user_ip = '',
                        agent_meta = aisecurity.generated_openapi_client.models.agent_meta.AgentMeta(
                            agent_id = '',
                            agent_version = '',
                            agent_arn = '', ), ),
                    contents = [
                        aisecurity.generated_openapi_client.models.scan_request_contents_inner.ScanRequestContentsInner(
                            prompt = '',
                            response = '',
                            code_prompt = '',
                            code_response = '',
                            context = '',
                            tool_event = aisecurity.generated_openapi_client.models.tool_event.ToolEvent(
                                input = '{"file_key":"abc123"}',
                                output = '{"content":[{"type":"text","text":"Fetched file"}]}', ), )
                        ], ),
        )
        """

    def testAsyncScanObject(self):
        """Test AsyncScanObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
