# Copyright (c) 2025, Palo Alto Networks
#
# Licensed under the Polyform Internal Use License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# https://polyformproject.org/licenses/internal-use/1.0.0
# (or)
# https://github.com/polyformproject/polyform-licenses/blob/76a278c4/PolyForm-Internal-Use-1.0.0.md
#
# As far as the law allows, the software comes as is, without any warranty
# or condition, and the licensor will not be liable to you for any damages
# arising out of these terms or the use or nature of the software, under
# any kind of legal claim.

"""
AISec API service

OpenAPI Specification for the AI Runtime Security API service

The version of the OpenAPI document: 0.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from aisecurity.generated_openapi_client.models.prompt_detection_details import PromptDetectionDetails


class TestPromptDetectionDetails(unittest.TestCase):
    """PromptDetectionDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptDetectionDetails:
        """Test PromptDetectionDetails
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PromptDetectionDetails`
        """
        model = PromptDetectionDetails()
        if include_optional:
            return PromptDetectionDetails(
                topic_guardrails_details = aisecurity.generated_openapi_client.models.topic_guard_rails.TopicGuardRails(
                    allowed_topics = [
                        ''
                        ],
                    blocked_topics = [
                        ''
                        ], ),
                toxic_content_details = aisecurity.generated_openapi_client.models.toxic_content_details.ToxicContentDetails(
                    toxic_categories = [
                        ''
                        ], )
            )
        else:
            return PromptDetectionDetails(
        )
        """

    def testPromptDetectionDetails(self):
        """Test PromptDetectionDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
